//LOGIN
export const ADD_LOGIN = "ADD_LOGIN";
export const LOGIN_LOADING = "LOGIN_LOADING";
export const LOGIN_FAILED = "LOGIN_FAILED";
export const REMOVE_LOGIN = "REMOVE_LOGIN";

//CATEGORY
export const POST_CATEGORY = "POST_CATEGORY";
export const FETCH_CATEGORY = "FETCH_CATEGORY";
export const FETCH_CATEGORYID = "FETCH_CATEGORYID";
export const EDIT_CATEGORY = "EDIT_CATEGORY";
export const DELETE_CATEGORY = "DELETE_CATEGORY";
export const CATEGORY_LOADING = "CATEGORY_LOADING";
export const CATEGORY_FAILED = "CATEGORY_FAILED";

//COMPANY
export const POST_COMPANY = "POST_COMPANY";
export const FETCH_COMPANY = "FETCH_COMPANY";
export const FETCH_COMPANYID = "FETCH_COMPANYID";
export const EDIT_COMPANY = "EDIT_COMPANY";
export const DELETE_COMPANY = "DELETE_COMPANY";
export const COMPANY_LOADING = "COMPANY_LOADING";
export const COMPANY_FAILED = "COMPANY_FAILED";

//PRODUCT
export const POST_PRODUCT = "POST_PRODUCT";
export const FETCH_PRODUCT = "FETCH_PRODUCT";
export const FETCH_PRODUCTID = "FETCH_PRODUCTID";
export const EDIT_PRODUCT = "EDIT_PRODUCT";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const PRODUCT_LOADING = "PRODUCT_LOADING";
export const PRODUCT_FAILED = "PRODUCT_FAILED";

//EXPENSE
export const POST_EXPENSE = "POST_EXPENSE";
export const FETCH_EXPENSE = "FETCH_EXPENSE";
export const FETCH_EXPENSEID = "FETCH_EXPENSEID";
export const EDIT_EXPENSE = "EDIT_EXPENSE";
export const DELETE_EXPENSE = "DELETE_EXPENSE";
export const EXPENSE_LOADING = "EXPENSE_LOADING";
export const EXPENSE_FAILED = "EXPENSE_FAILED";

//SUPPLIER
export const POST_SUPPLIER = "POST_SUPPLIER";
export const FETCH_SUPPLIER = "FETCH_SUPPLIER";
export const FETCH_SUPPLIERID = "FETCH_SUPPLIERID";
export const EDIT_SUPPLIER = "EDIT_SUPPLIER";
export const DELETE_SUPPLIER = "DELETE_SUPPLIER";
export const SUPPLIER_LOADING = "SUPPLIER_LOADING";
export const SUPPLIER_FAILED = "SUPPLIER_FAILED";

//CLIENT
export const POST_CLIENT = "POST_CLIENT";
export const FETCH_CLIENT = "FETCH_CLIENT";
export const FETCH_CLIENTID = "FETCH_CLIENTID";
export const EDIT_CLIENT = "EDIT_CLIENT";
export const DELETE_CLIENT = "DELETE_CLIENT";
export const CLIENT_LOADING = "CLIENT_LOADING";
export const CLIENT_FAILED = "CLIENT_FAILED";

//DASH
export const FETCH_DASH = "FETCH_DASH";
export const FETCH_ITEMWISE = "FETCH_ITEMWISE";
export const FETCH_DAILYSALE = "FETCH_DAILYSALE";
export const DELETE_DASH = "DELETE_DASH";
export const DASH_LOADING = "DASH_LOADING";
export const DASH_FAILED = "DASH_FAILED";

//BILLING
export const POST_BILLING = "POST_BILLING";
export const FETCH_BILLING = "FETCH_BILLING";
export const FETCH_BILLINGREPORT = "FETCH_BILLINGREPORT";
export const FETCH_BILLINGID = "FETCH_BILLINGID";
export const EDIT_BILLING = "EDIT_BILLING";
export const DELETE_BILLING = "DELETE_BILLING";
export const BILLING_LOADING = "BILLING_LOADING";
export const BILLING_FAILED = "BILLING_FAILED";

